# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testDockerUpamanyu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerupa.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4403709d994e4b0f97381293571aedde }}
        password: ${{ secrets.AzureAppService_ContainerPassword_58910444d69e450d8113aa8fd375aa5f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerupa.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4403709d994e4b0f97381293571aedde }}/studentmathpred:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testDockerUpamanyu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_829edf1d9db646839582a9c2a2bbacc1 }}
        images: 'testdockerupa.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4403709d994e4b0f97381293571aedde }}/studentmathpred:${{ github.sha }}'